#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [5.4, 5.5, 5.6]

before_script:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction --optimize-autoloader

script:
  #- ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  #- ./vendor/bin/phpcs --standard=PSR2 ./CodeSniffer/Standards/Goldstandard/Sniffs/
  - php -v

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 5
